swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
servers:
  - url: http://localhost:3001/api/v1/user/login/transactions
description: Serveur principal de l'application

paths:
  /transactions:
    get:
      summary: Voir les transactions du mois en cours
      description: Affiche toutes les transactions de l'utilisateur pour le mois en cours, groupées par compte.
      responses:
        "200":
          description: Liste des transactions trouvée
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "500":
          description: Erreur du serveur

    post:
      summary: Créer une nouvelle transaction
      description: Permet d'ajouter une nouvelle transaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionInput"
      responses:
        "201":
          description: Transaction créée avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "400":
          description: Mauvaise requête
        "500":
          description: Erreur du serveur

  /transactions/{transactionId}:
    get:
      summary: Voir les détails d'une transaction
      description: Affiche toutes les informations sur une seule transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
          description: L'ID de la transaction à consulter
      responses:
        "200":
          description: Détails de la transaction
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "404":
          description: Transaction non trouvée

    put:
      summary: Modifier une transaction
      description: Permet de modifier une transaction existante.
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
          description: L'ID de la transaction à modifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionInput"
      responses:
        "200":
          description: Transaction mise à jour
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "404":
          description: Transaction non trouvée

    delete:
      summary: Supprimer une transaction
      description: Permet de supprimer une transaction.
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
          description: L'ID de la transaction à supprimer
      responses:
        "204":
          description: Transaction supprimée (aucun contenu retourné)
        "404":
          description: Transaction non trouvée

components:
  schemas:
    Transaction:
      type: object
      properties:
        transactionId:
          type: string
          example: "abc123"
        date:
          type: string
          format: date
          example: "2025-05-06"
        montant:
          type: number
          format: float
          example: 49.99
        description:
          type: string
          example: "Achat supermarché"
        compteId:
          type: string
          example: "compte1"

    TransactionInput:
      type: object
      required:
        - date
        - montant
        - description
        - compteId
      properties:
        date:
          type: string
          format: date
          example: "2025-05-06"
        montant:
          type: number
          format: float
          example: 49.99
        description:
          type: string
          example: "Achat supermarché"
        compteId:
          type: string
          example: "compte1"
